services:
  postgres:
    image: postgres:latest
    container_name: eshop_postgres
    environment:
      POSTGRES_USER: Illona
      POSTGRES_PASSWORD: Illona55
      POSTGRES_DB: eshop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - eshop_network

  product:  # 🔁 Nom en minuscules obligatoire
    build: 
      context: ../Product
      dockerfile: Dockerfile
    container_name: products_api
    environment:
      DATABASE_URL: postgres://Illona:Illona55@postgres:5432/eshop
      PORT: 3030
    ports:
      - "3030:3030"
    depends_on:
      - postgres
    networks:
      - eshop_network

  gateway:
    build: 
      context: ../Gateway-proxy
      dockerfile: Dockerfile
    container_name: eshop_gateway
    environment:
      PRODUCTS_SERVICE_URL: http://product:3030  # 🔁 correspond au nom du service ci-dessus
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - product
    networks:
      - eshop_network

  frontend:
    build: 
      context: ../frontend
      dockerfile: Dockerfile
    container_name: eshop_frontend
    environment:
      API_GATEWAY_URL: http://gateway:3001  # 🔁 corrige le port ici
    ports:
      - "3000:3000"
    depends_on:
      - gateway
    networks:
      - eshop_network

volumes:
  postgres_data:
    driver: local

networks:
  eshop_network:
    driver: bridge
